### ISSUE TITLE
[Rule Tuning] Attempts to Brute Force an Okta User Account

### ISSUE THREAD

**Issue by threat-punter** [elastic/detection-rules#1201]
## Link to rule
https://github.com/elastic/detection-rules/blob/92eaa5b18ab4d613e1adc39732c491f54682035a/rules/okta/credential_access_attempts_to_brute_force_okta_user_account.toml

## Description

Update threshold rule to use `okta.actor.alternate_id`.

See discussion under https://github.com/elastic/detection-rules/issues/1172 for context.

https://github.com/elastic/detection-rules/blob/92eaa5b18ab4d613e1adc39732c491f54682035a/rules/okta/credential_access_attempts_to_brute_force_okta_user_account.toml#L48

**Comment by BenB196** [comment]
@threat-punter just an FYI, I don't think ```okta.target.alternate_id``` is what you want for this rule. It doesn't look like this event contains the ```okta.target.alternate_id``` field. I think ```okta.actor.alternate_id``` would be the correct field, for getting the human readable value.

**Comment by threat-punter** [comment]
Good eye @BenB196. I'll update the comment. 👍

**Comment by austinsonger** [comment]
@threat-punter You want me to update my PR

**Comment by austinsonger** [comment]
I updated my PR #1200

**Comment by BCall-BT** [comment]
@austinsonger @BenB196 @threat-punter 
I do not understand why the change was made from `okta.actor.id` to okta.actor.alternate_id`, this references the same account info just adding an email domain suffix. You will still have a high rate of False Positives due to the Okta "System" account being involved in all reset transactions. 

If you group by "user.targeet.full_name" you will focus on the account that is actually being reset, not the ID making the request. This will have the effect of greatly reducing False Positives while also increasing the True Positive rate.

For example:
Both Bob and Alice are trying to reset their passwords within the same search window (the larger the org the higher the chances of this happening), defending in the reset method, and if they have issues or not, you will see multiple log entries with the majority of them being the Okta System account.  If Alice's account was 2 with the system account Bob's had 3, the alert would trigger because the rule saw 5 events with the same okta.actor.id, even though neither Bob nor Alices actually had 5 events. 

On the other hand, a bad actor was trying to gain access to Chales's account but logs showed 4 events with the Okta system ID and 4 with Charles. This attack would not be detected with the current rule logic.

Switching to user.targeet.full_name would trigger the alert on Charles's account and not for Alice and Bob.
